### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [PiperKev/mark-twain_puddnhead-wilson#1]
- [x] We use `<strong>` for shouting, not formatting; see [SEMoS 8.3.3](https://standardebooks.org/manual/1.7.3/single-page#8.3.3). David Wilson's sign is not shouting. :)
- [x] Chapter 2, in Roxy's dialog starting with "Bless yo’ soul…," there is a "’ca’se” missing in "but dat’s … it’s mine”.
- [x] Strong emphasis follows the same rules as regular emphasis (italics); the exclamation point should not be in the "down the river" tag because it's not a separate clause ([SEMoS 8.2.4](https://standardebooks.org/manual/1.7.3/single-page#8.2.4).
- [x] Modernize spelling removed the hyphens from "fel-low" in the song in chapter 11; they are there for the same reason as the ones in fe-el-low, and should not be removed (and should be non-break hyphens).
- [x] Same for the "hel-lo" earlier in the chapter. The changes made by the automated tools always need to be manually reviewed to make sure that unwanted changes weren't made.
- [x] And same for the one in "Ye-s" in chapter 18. (You made a manual change for this one, but typogrify currently always replaces NBH with hyphens. The next release of the tools will move the identifying of NBH to find-unusual-characters.)
- [x] Putting the epub:type in the chapter epigraph `cite`s rather than on separate `i` tags means the book titles aren't italicized as they should be.
- [x] The `strong` element doesn't take text-align or indent CSS; those are parent element items.
- [x] The lines labeled "verse" in chapter 11 are immediately preceded by "… while the house bellowed forth in **song**:".
- [x] Where did the chapter titles come from? They're not in the scans.
- [x] The author NACOAF URI should be for the author (Mark Twain), not Samuel Clemens.
- [x] PGDP is listed in the colophon but not the metadata, nor are they listed on Gutenberg.
- [x] Given the epigraph from a fictitious book, and the general tone of the preface, I'm not sure it could be considered non-fiction?
- [x] I haven't read the book—is the child-swap a known fact throughout the book, i.e. from the first chapter or so? If so, then no problem, but if not, it shouldn't be mentioned in the long description—we don't want to give away plot points in the description.
- [x] No change needed, but a suggestion for the future… We want to keep commits to a single task, but a single task made in multiple files is still a single task. Thus, formatting the chapter headers (one task) and formatting the italics (one task) can be done for all the files at once, so that there are two commits for those two tasks rather than forty-four commits for those two tasks.
- [x] Also (again, for the future), please be as specific as possible (and as general as necessary) in your commit messages. If you're doing multiple semantic-related things, than "Manual semantic changes" is fine. But if all you're doing is formatting italics, then "Semanticate italics" provides more information to someone looking at the history.

**Comment by PiperKev** [comment]
_Where did the chapter titles come from? They're not in the scans._

They were in the PG transcription, and also in a few editions of the book, including this 1922 edition:

 https://archive.org/details/puddnheadwilsone0000mark

**Comment by PiperKev** [comment]
_Putting the epub:type in the chapter epigraph cites rather than on separate i tags means the book titles aren't italicized as they should be._

Should I leave off the <cite> tags, then, or the <i> tags?

**Comment by vr8hub** [comment]
Then the edition the titles are from needs to be listed as a scan source, with a publication note about why there are two.

**Comment by vr8hub** [comment]
Your other comment was cutoff, but you obviously should not leave off a valid tag.

**Comment by PiperKev** [comment]
> Your other comment was cutoff, but you obviously should not leave off a valid tag.

Yeah, I don't know what happened with the comment.  Should I delete the selectors for epigraph cites in local.css since currently they're set for small caps?  And I know you didn't mention it, but should I delete the italics selector for epigraphs as well, since the chapter epigraphs in the book aren't in italics and those are the only epigraphs in this particular book??

**Comment by PiperKev** [comment]
Disregard my last, I had a brain fart.  All issues addressed.
